apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: jetstack/cert-manager
      sourceRef:
        kind: HelmRepository
        name: flux-cert-manager
        namespace: flux-system
      version: v1.13.2
  interval: 1h0m0s
  values:
    installCRDs: true