---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-cloudflare-key-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-secret-store # Must match SecretStore on the cluster
  target:
    name: external-cloudflare-api-token # Name for the secret to be created on the cluster
    creationPolicy: Owner
  data:
    - secretKey: api-key # Key given to the secret to be created on the cluster
      remoteRef:
        key: CF_API_KEY # Key of the variable on Gitlab
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-cloudflare-mail-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-cluster-secret-store # Must match SecretStore on the cluster
  target:
    name: external-cloudflare-user-mail # Name for the secret to be created on the cluster
    creationPolicy: Owner
  data:
    - secretKey: user-mail # Key given to the secret to be created on the cluster
      remoteRef:
        key: CF_USER_MAIL # Key of the variable on Gitlab