apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
    #Le nom du chart que l'on souhaite installer
      chart: ingress-nginx
      #La référence vers le repository Helm (déclaré dans le fichier /flux/repository/helm/nginx.yaml)
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-controller
        namespace: flux-system
      #La version du chart que l'on souhaite installer
      version: 4.9.0
  interval: 1h0m0s
  #Les valeurs que l'on souhaite passer au chart
  values: 
    controller:
      publishService: 
        enabled: true