---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-gitlabcred
  namespace: kyverno
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gitlab-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gitlabcred
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{\"auths\":{\"registry.gitlab.com\":{\"username\":\"{{ .username }}\",\"password\":\"{{ .password }}\",\"auth\":\"{{(printf \"%s:%s\" .username .password) | b64enc }}\"}}}"
  data:
    - secretKey: username
      remoteRef:
        key: gl_cr_username
    - secretKey: password
      remoteRef:
        key: gl_cr_password
