apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-external-dns
resources:
- ns.yaml
- ../external-dns-rbac.yml
- ../../external-secrets/external-dns-cloudflare.yml

