apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.labName }}
  template:
    metadata:
      labels:
        app: {{ .Values.labName }}
    spec:
      containers:
      - image: {{ .Values.pod.image }}:{{ .Values.pod.version }}
        name: {{ .Values.labName }}
        ports:
        - containerPort: 80
