apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demos 
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./demos/flux
  prune: true
  dependsOn:
  - name: cert-manager
  - name: external-dns
  sourceRef:
    kind: GitRepository
    name: flux-system
