apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./external-dns/flux
  prune: true
  dependsOn:
    - name: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system