apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-downscaler 
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kube-downscaler/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
