apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./nginx-ingress-controller/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
